### ISSUE TITLE
Learn parses this as a quiz. 

### ISSUE THREAD

**Issue by talum** [learn-co-curriculum/immersive-week-1-discussion-questions#8]
We need to reformat this so that it doesn't get deployed as a quiz. 

This is the regex matcher `QUIZ_BLOCKS      = /\?{3}\s*?(.+?)\?{3}/m`.

If there are blocks that match that, Learn will create a "quiz assessment" in addition to the basic "signature assessment".

**Comment by SammySteiner** [comment]
@talum Hey, can we get this taken care of? The lack of a check mark here is driving me nuts :)

There are also a bunch of other issues on this lesson that mention the same thing.

**Comment by alexgriff** [comment]
Changed Triple `???` to single or double `?`. Resolved
